### ISSUE TITLE
Build sh4 with gcc4.9.4

### ISSUE THREAD

**Issue by kueken** [MastaG/meta-fulan#1]
only one info

You can just try it.
No stm.patch is required.

Image is a little bit smaller and the box runs well.

**Comment by MastaG** [comment]
Hi kueken,

Thank you for letting me know, I'll switch to the default gcc 4.9.4 compiler then :)
Did you also try more recent versions of gcc? such as 6.2.x for example?

**Comment by kueken** [comment]
Hi
gcc6 .. is certainly not possible. sh is no longer contained there.
gcc 5.4 should still be possible.
However, the 4.9.4 is more up-to-date and faster, I think.
I can also make Pullrequest?

greeting

**Comment by MastaG** [comment]
Of course my friend :)

Op 13 sep. 2017 18:21 schreef "kueken" <notifications@github.com>:
