### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by kueken** [MastaG/meta-fulan#3]
Hello

I tried to build an image out of "pyro" and "rocko".
Unfortunately, at the end of the build process, the rootfs crash with an error.

**Comment by MastaG** [comment]
That's correct, you need to remove the meta-raspberrypi from your build/conf/bblayers.conf file.
This BSP is still WIP.

The errors about the base hash values changed can ignored. The image should work.

**Comment by kueken** [comment]
Ah..
Thanks
